### ISSUE TITLE
"Can't find variable: topics" and "Connection refused: Unacceptable protocol version"

### ISSUE THREAD

**Issue by L-U-C-K-Y** [qiscus/qiscus-sdk-web-core#65] opened 2020-12-09 19:29 UTC
Hi Qiscus Team 👋🏼

I noticed the following errors in our Sentry logs:

1800 errors within a day with this message:

```typescript
ReferenceError: Can't find variable: topics
```

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/14868134/101677602-0ed2d600-3a5d-11eb-9ab3-5f85d08bec34.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/14868134/101677624-15f9e400-3a5d-11eb-9ff4-20646c1c9321.png">

377 errors within a day with this message:

```typescript
Error: Connection refused: Unacceptable protocol version
```

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/14868134/101677435-ddf2a100-3a5c-11eb-813d-ef4e96d01034.png">

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/14868134/101677493-eea31700-3a5c-11eb-9ee1-2b81bd8149d6.png">

We are running "qiscus-sdk-core": "2.10.4".

**Comment by adicatur** [comment] 2020-12-14 09:14
Hi @L-U-C-K-Y can we know when last time do you get this issue?

**Comment by L-U-C-K-Y** [comment] 2020-12-14 09:31
Hi @adicatur 

Many thanks for your reply!

Last time I have received this error is 25 minutes ago, here more context regarding the error, seems to only happen in Safari:

![image](https://user-images.githubusercontent.com/14868134/102064378-84d99300-3df7-11eb-808c-76b2dbec4380.png)

**Comment by adicatur** [comment] 2020-12-15 09:18
Ok, thanks for the info will check @L-U-C-K-Y , and let us know if you find a new error, it will help us to find the pattern

**Comment by adicatur** [comment] 2020-12-15 09:22
Btw @L-U-C-K-Y the timestamp in your image is UTC or is it your timezone? if it's in your timezone can we know what timezone do you use?

**Comment by L-U-C-K-Y** [comment] 2020-12-15 10:09
Hi @adicatur 

Time is UTC+1.

I am deploying the newest 2.10.x version too, to see if it resolves the issue, will keep you posted.

**Comment by adicatur** [comment] 2020-12-16 03:46
Ok thanks @L-U-C-K-Y , we will update also once we have the findings

**Comment by L-U-C-K-Y** [comment] 2020-12-16 13:24
It seems that after updating to the latest version, this issue seems not to come up anymore, I'll continue monitoring.

**Comment by L-U-C-K-Y** [comment] 2020-12-18 13:41
OK, hmm it seems that this issue persists, it's seriously clogging our sentry:

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/14868134/102620886-08b8b580-413f-11eb-8158-39e369e37cf1.png">

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/14868134/102620918-13734a80-413f-11eb-99a8-0c39c2870e66.png">

**Comment by adicatur** [comment] 2020-12-21 04:33
Hi @L-U-C-K-Y ok thanks for your report, as per now we still cannot reproduce this issue, but we will investigate deeper and will let you know the update

**Comment by apiep** [comment] 2020-12-21 05:33
Hi @L-U-C-K-Y I just published a new version containing fix for undefined variable "topics" with version of 2.10.7, could you try it?

**Comment by L-U-C-K-Y** [comment] 2020-12-21 17:39
Thanks @apiep, will check and report back!

**Comment by apiep** [comment] 2021-01-05 04:36
Will close this issue for now, feel free to re-open if it is still exists

**Closed by apiep** 2021-01-05 04:36 UTC
